dataset:
  orig_dir: "data"
  train_dir: "output/decoded"
  val_dir: "output/decoded"
  test_dir: "output/decoded"

dataloader:
  batch_size: 16 # Increased for RTX 5070
  val_batch_size: 4
  num_workers: 8 # More workers to feed that fast GPU

enhancer:
  implementation: "res"
  input_shape: [11, 128, 128]
  activation: "prelu"
  reflect_padding: true
  save_to: "experiments/enhancer/vtm_res_v3.pth"
  load_from: null
  structure:
    blocks:
      - { num_layers: 2, features: 64, kernel_size: 3, padding: 1 }
      - { num_layers: 2, features: 64, kernel_size: 3, padding: 1 }
      - { num_layers: 2, features: 64, kernel_size: 3, padding: 1 }
      - { num_layers: 2, features: 64, kernel_size: 3, padding: 1 }
      - { num_layers: 2, features: 64, kernel_size: 3, padding: 1 }
      # - kernel_size: 3
      #   padding: 1
      #   features: 64
      # - kernel_size: 3
      #   padding: 1
      #   features: 64
      # - kernel_size: 3
      #   padding: 1
      #   features: 64
  output_block:
    features: 3
    kernel_size: 3
    padding: 1
    stride: 1
    tanh: false

trainer:
  mode: "enhancer"
  enhancer:
    epochs: 200
    enhancer_lr: 0.0001
    num_samples: 4
    enhancer_scheduler: True
    enhancer_scheduler_gamma: 0.5
    enhancer_scheduler_milestones: [50, 100, 150]
